import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Box, Container } from '@chakra-ui/react';

import useCurrentLocation from '@/hooks/useCurrentLocation';
import Map from '@/components/Map';
import ChargerDetail from '@/components/ChargerDetail';
import AddressSelector from '@/components/AddressSelector';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { currentLocation, isLocationFound } = useCurrentLocation();

  return (
    <>
      <Head>
        <title>전기차지 | 충전소 찾기</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container className={inter.className} maxW='8xl' p={0}>
        <Box>
          <AddressSelector currentLocation={currentLocation} />
          <Map isLocationFound={isLocationFound} currentLocation={currentLocation} />
        </Box>
        <ChargerDetail isLocationFound={isLocationFound} />
      </Container>
    </>
  );
}
