import { Inter } from 'next/font/google';
import { Button } from '@chakra-ui/react';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={inter.className}>
        <Button colorScheme='blue'>검색</Button>
        <Button>내 주변</Button>
      </main>
    </>
  );
}
